local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("AnhaHUB", "Synapse")
local Tab = Window:NewTab("Main")
local Section = Tab:NewSection("Dupe")

Section:NewTextBox("Custom Item", "", function(txt)
	game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(txt)
end)
Section:NewButton("Dupe MONEY🤑", "dupe", function()
    local args = {
    [1] = "Reward"
}

game:GetService("ReplicatedStorage"):WaitForChild("RemoteEvents"):WaitForChild("FireTrigger"):FireServer(unpack(args))

end)
Section:NewButton("Dupe harambe", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Box Toy Harambe")
end)
Section:NewButton("Dupe Lem ", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Box Toy Lem")
end)
Section:NewButton("Dupe sandman", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Box Toy SandMan")
end)
Section:NewButton("Dupe sanic", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Box Toy Sanic")
end)
Section:NewButton("Dupe house", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Box Toy House")
end)
Section:NewButton("Dupe noob", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Box Toy Noob")
end)
Section:NewButton("Dupe box toy", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Box Toy Box Toy")
end)
Section:NewButton("Dupe Egg", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Box Toy Egg")
end)
Section:NewButton("Dupe Air", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Box Toy Air")
end)
Section:NewButton("Dupe dart", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Dart")
end)
Section:NewButton("Dupe bike", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Retro Bike")
end)
Section:NewButton("Dupe ooze", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Green Ooze")
end)
Section:NewButton("Dupe walky", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Walky Talky")
end)
Section:NewButton("Dupe demogorgan", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Demogorgan")
end)
Section:NewButton("Dupe demogorgan uwu", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Demogorgan Kawaii")
end)
Section:NewButton("Dupe Zushi", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Zushi Zushi")
end)
Section:NewButton("Dupe Puzzle Key", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Puzzle Key")
end)
Section:NewButton("Dupe Puzzler Head", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Puzzler Head")
end)
Section:NewButton("Dupe Lil Hacker", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Lil Dude")
end)
Section:NewButton("Dupe Seriously Dude", "dupe", function()
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer("Lil Dude Real")
end)
local Tab = Window:NewTab("Admin Scripts")
local Section = Tab:NewSection("Admin scripts")
Section:NewButton("Inf Yield", "fe admin", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
local Tab = Window:NewTab("Credits")
local Section = Tab:NewSection("Owner: Anha#4156")
local Section = Tab:NewSection("Creator: Anha#4156")

print("Script succefully loaded")
print("Owner: Anha#4156")
print("Creator: Anha#4156")
